import { unzipSync } from "fflate";
import { mkdir, writeFile, rm } from "node:fs/promises";
import path from "node:path";

const PARTS = [
  ["1-KsfXz30pc3cy-k7zFsl5YHHIuxUZQOw", "water-colors-originals-part-1.zip"],
  ["10vBBhmZ8c_3ENxziSxdK_o5bzX24rUTW", "water-colors-originals-part-2.zip"],
  ["1EPflkZ5FOUc3zImFkqGRbFB6Y7-Fe4Yx", "water-colors-originals-part-3.zip"],
];

const IDEAS = [
{"notion":"https://app.notion.com/3abbd701fac9813b932ede5cbbbc2ba5","title":"Танцующая собака в ванне: каждый бит меняет цвет воды","date":"2026-07-29","session":"Утро","score":8.0,"speed":"Уже массовый","hook":"Начать сразу с нелепо серьёзной собаки в пустой белой ванне; на первом ударе вода становится неоново-синей.","source":"https://www.tikwm.com/video/7660227517592210695.html","status":"На проверку","types":["Trend-jack","AI animals","Satisfying","Meme"],"recommendation":"Запасной формат","id":"idea-01"},
{"notion":"https://app.notion.com/3abbd701fac9816ea2cde1873f743b38","title":"Три AI-котёнка танцуют в раковине и вызывают три цветовых взрыва","date":"2026-07-29","session":"Утро","score":9.0,"speed":"Растёт","hook":"Кто из троих первым испортит чистую воду? Первый взрыв цвета — в первые 1,5 секунды.","source":"https://knowyourmeme.com/memes/three-kittens-dancing-the-dark-triad","status":"На проверку","types":["Trend-jack","AI animals","Interactive","Meme"],"recommendation":"Сильный тест","id":"idea-02"},
{"notion":"https://app.notion.com/3abbd701fac98173b345e868fd0065d8","title":"Спаси серую каплю: зрители выбирают, какой цвет вернуть ей завтра","date":"2026-07-29","session":"Утро","score":7.0,"speed":"Только появился","hook":"Маленькая бесцветная капля смотрит на ярких персонажей; зрители выбирают, какой цвет подарить ей в следующей серии.","source":"https://ads.tiktok.com/business/creativecenter/","status":"На проверку","types":["Story","Interactive","AI animals","Live bridge"],"recommendation":"Низкий приоритет","id":"idea-03"},
{"notion":"https://app.notion.com/3abbd701fac98189b111c3415478e7da","title":"Color Squad: капли-персонажи выходят танцевать по очереди","date":"2026-07-29","session":"Утро","score":8.0,"speed":"Растёт","hook":"Новый персонаж входит каждые 1–1,5 секунды; зритель ждёт появления последнего цвета.","source":"https://lightreel.ai/blogs/whats-trending-on-tiktok","status":"На проверку","types":["Trend-jack","AI animals","Interactive","Meme"],"recommendation":"Запасной формат","id":"idea-04"},
{"notion":"https://app.notion.com/3abbd701fac9819799e2d50b8c29c0c1","title":"Невозможная жидкость: вода → хром → стекло → галактика → краска","date":"2026-07-29","session":"Утро","score":7.0,"speed":"Растёт","hook":"Первое превращение на 0,3 секунде; зритель выбирает, какой режим оставить навсегда.","source":"https://lightreel.ai/blogs/whats-trending-on-tiktok","status":"На проверку","types":["Satisfying","Trend-jack"],"recommendation":"Низкий приоритет","id":"idea-05"},
{"notion":"https://app.notion.com/3acbd701fac9810993d7d15e9e482a92","title":"He Was Whipping Up Actual Happiness — в раковине","date":"2026-07-29","session":"Утро","score":9.0,"speed":"Только появился","hook":"Серьёзный маленький шеф мешает мутную воду; на ключевой фразе она взрывается радужным облаком.","source":"https://www.tiktok.com/music/original-sound-7666399271989693215","status":"На проверку","types":["Trend-jack","Meme","Satisfying"],"recommendation":"Сильный тест","id":"idea-06"},
{"notion":"https://app.notion.com/3acbd701fac9816c8390f358bb20e21c","title":"Сколько оттенков ты видишь в жидкой радуге?","date":"2026-07-29","session":"Утро","score":8.0,"speed":"Растёт","hook":"У тебя пять секунд: сколько отдельных цветов ты видишь в почти одинаковых полосах?","source":"https://www.tiktok.com/search?q=tetrachromat%20color%20test","status":"На проверку","types":["Interactive","Satisfying"],"recommendation":"Запасной формат","id":"idea-07"},
{"notion":"https://app.notion.com/3acbd701fac981c582e8d7c650a90e30","title":"Attention Seeker: серая капля превращается в неоновую диву","date":"2026-07-29","session":"Утро","score":9.0,"speed":"Растёт","hook":"Серая капля отворачивается, а на бит резко становится зеркально-радужной и начинает позировать.","source":"https://www.tiktok.com/music/original-sound-7661168677693279009","status":"На проверку","types":["Trend-jack","Meme","Satisfying"],"recommendation":"Сильный тест","id":"idea-08"},
{"notion":"https://app.notion.com/3acbd701fac981d0a383e48987a8c77d","title":"Get These Muddy Drops Out of Here","date":"2026-07-29","session":"Утро","score":8.0,"speed":"Растёт","hook":"Королевский кот у золотого крана замечает грязные капли и требует убрать попрошаек.","source":"https://www.tiktok.com/music/original-sound-7646826307149450015","status":"На проверку","types":["Trend-jack","AI animals","Meme"],"recommendation":"Запасной формат","id":"idea-09"},
{"notion":"https://app.notion.com/3acbd701fac9813e9d4ada9ac719eda3","title":"Mhm, I Got the Color: жёлтая капля украла всю палитру","date":"2026-07-29","session":"День","score":8.0,"speed":"Только появился","hook":"Самодовольная жёлтая капля поднимает кусок цветового сыра, а остальные оттенки исчезают.","source":"https://www.tiktok.com/@moteaeats/video/7665516534638316813","status":"На проверку","types":["Trend-jack","Meme","Story"],"recommendation":"Запасной формат","id":"idea-10"},
{"notion":"https://app.notion.com/3acbd701fac98192a3d7d0e0a45d53d1","title":"Wax Crack Rainbow: сломай цветную корку над водой","date":"2026-07-29","session":"День","score":8.0,"speed":"Только появился","hook":"Тонкая радужная корка ломается, а под ней раскрываются облака краски. Какой цвет треснет первым?","source":"https://www.tiktok.com/search?q=wax%20cracking%20asmr","status":"На проверку","types":["Satisfying","Interactive"],"recommendation":"Запасной формат","id":"idea-11"},
{"notion":"https://app.notion.com/3acbd701fac981968a8ee5dbf8a54251","title":"Baby You Buggin: три цветовые капли ломают физику танцем","date":"2026-07-29","session":"День","score":9.0,"speed":"Растёт","hook":"На каждом движении капля меняет форму, цвет и гравитацию.","source":"https://www.tiktok.com/search?q=baby%20you%20buggin","status":"На проверку","types":["Trend-jack","Meme","Satisfying"],"recommendation":"Сильный тест","id":"idea-12"},
{"notion":"https://app.notion.com/3acbd701fac981c399cbc57325161d3e","title":"REDRED Complement Switch: красный танец внезапно становится голубым","date":"2026-07-29","session":"День","score":8.5,"speed":"Растёт","hook":"Два красных маскота повторяют резкую хореографию; последний удар полностью переворачивает цвет в cyan.","source":"https://www.tiktok.com/search?q=redred%20dance%20challenge","status":"На проверку","types":["Trend-jack","Satisfying","Meme"],"recommendation":"Тестировать","id":"idea-13"},
{"notion":"https://app.notion.com/3acbd701fac9814b9299e678947d14f0","title":"No No No: раковина отказывается принимать обычные цвета","date":"2026-07-29","session":"Вечер","score":7.0,"speed":"Растёт","hook":"Красная и синяя капли отвергнуты; голографическая радуга получает идеальный водоворот.","source":"https://www.tiktok.com/music/original-sound-7637599604683016991","status":"На проверку","types":["Trend-jack","Interactive","Meme","Satisfying"],"recommendation":"Низкий приоритет","id":"idea-14"},
{"notion":"https://app.notion.com/3acbd701fac98158a2c9e4ca130df68a","title":"Foam Look: после струи кот поворачивается — и пена меняет цвет","date":"2026-07-29","session":"Вечер","score":9.0,"speed":"Растёт","hook":"Струя попадает сзади, кот медленно оборачивается с фирменным взглядом — вся ванна становится неоновой.","source":"https://x.com/Fun_Viral_Vids/status/2079593191829880949","status":"На проверку","types":["Trend-jack","AI animals","Meme","Satisfying"],"recommendation":"Сильный тест","id":"idea-15"},
{"notion":"https://app.notion.com/3acbd701fac9817b8111c9f7b8959de7","title":"That’s Triggering Me: одна капля чуть-чуть неправильного оттенка","date":"2026-07-29","session":"Вечер","score":8.0,"speed":"Растёт","hook":"Почти идеальная палитра ломается одной неправильной каплей; зритель должен найти её до reveal.","source":"https://www.tiktok.com/search?q=thats%20triggering%20me%20trend","status":"На проверку","types":["Trend-jack","Interactive","Satisfying","Meme"],"recommendation":"Запасной формат","id":"idea-16"},
{"notion":"https://app.notion.com/3acbd701fac981b28f95b771c3f14d22","title":"1,000 Tiny Colors: маленькие моменты, когда вода выглядит идеально","date":"2026-07-29","session":"Вечер","score":7.0,"speed":"Растёт","hook":"Серия микромоментов по 0,5 секунды: радужный блик, пузырь, цветная тень, тонкая волна.","source":"https://www.tiktok.com/search?q=1000%20tiny%20moments%20trend","status":"На проверку","types":["Trend-jack","Satisfying","Story"],"recommendation":"Низкий приоритет","id":"idea-17"},
{"notion":"https://app.notion.com/3acbd701fac981f41ada1abf5f68828e","title":"Найди AI: четыре танцора, один постепенно ломается","date":"2026-07-29","session":"Вечер","score":8.0,"speed":"Растёт","hook":"Четыре почти одинаковых танцора; один начинает нарушать анатомию. Зритель должен заметить первым.","source":"https://www.tiktok.com/search?q=spot%20the%20ai%20challenge","status":"На проверку","types":["Trend-jack","Interactive","Meme"],"recommendation":"Запасной формат","id":"idea-18"},
{"notion":"https://app.notion.com/3acbd701fac981f6729fd96e4f37f32c","title":"Meltwater Stillness: весь хаос застыл, двигается только маленький герой","date":"2026-07-29","session":"Вечер","score":8.0,"speed":"Только появился","hook":"Вся сцена замерла в сложном всплеске; только крошечный персонаж идёт через неё как по льду.","source":"https://www.tiktok.com/search?q=frozen%20time%20ai%20video","status":"На проверку","types":["Trend-jack","Story","Satisfying"],"recommendation":"Запасной формат","id":"idea-19"},
{"notion":"https://app.notion.com/3acbd701fac9816c80cc9c0ea526ba45","title":"Mop Man: кот-уборщик внезапно выдаёт олимпийский танец","date":"2026-07-29","session":"Вечер","score":9.0,"speed":"Только появился","hook":"Кот лениво моет пол, затем внезапно делает worm, шпагат и бешеный танец — и невозмутимо продолжает уборку.","source":"https://www.tiktok.com/search?q=mop%20man%20dance%20trend","status":"На проверку","types":["Trend-jack","AI animals","Meme"],"recommendation":"Сильный тест","id":"idea-20"},
{"notion":"https://app.notion.com/3adbd701fac98119b8b7f52f1adb1497","title":"COISAS ABSURDAS: парад невозможных существ с одной хореографией","date":"2026-07-30","session":"Утро","score":9.0,"speed":"Растёт","hook":"Каждый новый зверь ещё абсурднее предыдущего, но все идеально синхронны.","source":"https://www.tiktok.com/search?q=coisas%20absurdas%20trend","status":"На проверку","types":["Trend-jack","AI animals","Meme"],"recommendation":"Сильный тест","id":"idea-21"},
{"notion":"https://app.notion.com/3adbd701fac98110bcb7d00de20ee6ff","title":"WHIPPING UP IN A KETTLE: кот варит настоящее счастье","date":"2026-07-30","session":"Утро","score":8.5,"speed":"Растёт","hook":"Кот-шеф мешает пустой чайник, а на бит из него вырывается цветное счастье.","source":"https://www.tiktok.com/search?q=whipping%20up%20happiness%20trend","status":"На проверку","types":["Trend-jack","AI animals","Meme"],"recommendation":"Тестировать","id":"idea-22"},
{"notion":"https://app.notion.com/3adbd701fac981e893ec9941bcb22b08","title":"BESIDES THE OBVIOUS: AI-пёс провоцирует кота","date":"2026-07-30","session":"Утро","score":8.0,"speed":"Растёт","hook":"Пёс делает очевидную гадость, но кот замечает совсем другую деталь и взрывается.","source":"https://www.tiktok.com/search?q=besides%20the%20obvious%20trend","status":"На проверку","types":["Trend-jack","AI animals","Meme"],"recommendation":"Запасной формат","id":"idea-23"},
{"notion":"https://app.notion.com/3adbd701fac98185a3e79d6b9507d853","title":"GET THESE BEGGARS OUT: кот-король и армия просителей","date":"2026-07-30","session":"Утро","score":8.5,"speed":"Только появился","hook":"Кот-король требует выгнать просителей, но каждый оказывается ещё более нелепым.","source":"https://www.tiktok.com/search?q=get%20these%20beggars%20out%20trend","status":"На проверку","types":["Trend-jack","AI animals","Story","Meme"],"recommendation":"Тестировать","id":"idea-24"},
{"notion":"https://app.notion.com/3adbd701fac9817a9f0ce8f2cc4d7c03","title":"ALL OF US / NONE OF US: маскоты исчезают по голосованию","date":"2026-07-30","session":"Утро","score":9.0,"speed":"Растёт","hook":"Четыре маскота стоят в ряд, комментарии решают, кто исчезнет в следующем ролике.","source":"https://www.tiktok.com/search?q=all%20of%20us%20none%20of%20us%20trend","status":"На проверку","types":["Trend-jack","Interactive","Meme"],"recommendation":"Сильный тест","id":"idea-25"},
{"notion":"https://app.notion.com/3adbd701fac981122b998e02e048198d","title":"Jimothy Compression Curse: весь мир становится коротким и круглым","date":"2026-07-30","session":"Утро","score":9.5,"speed":"Растёт","hook":"Машина, хлеб, диван и планета сжимаются в круглую форму енота; настоящий Jimothy спокойно проходит мимо.","source":"https://www.tiktok.com/search?q=jimothy%20compression%20curse","status":"На проверку","types":["Trend-jack","AI animals","Meme","Satisfying"],"recommendation":"Стартовать первой","id":"idea-26"},
{"notion":"https://app.notion.com/3adbd701fac98187a0f32d3fae976fd2","title":"John Rod Solos Everything: две светящиеся палки режут любую реальность","date":"2026-07-30","session":"Утро","score":8.5,"speed":"Растёт","hook":"Две простые палки разрезают всё: дверь, облако, воду и сам видеокадр.","source":"https://www.tiktok.com/search?q=john%20rod%20solos%20everything","status":"На проверку","types":["Trend-jack","Meme","Satisfying"],"recommendation":"Тестировать","id":"idea-27"},
{"notion":"https://app.notion.com/3adbd701fac981d9a0a171299fd24a23","title":"Huss Valley Delivery Run: хомяк доставляет посылку сквозь кошмарную долину","date":"2026-07-30","session":"Утро","score":8.5,"speed":"Растёт","hook":"Маленький курьер проходит всё более страшные локации, но ни разу не роняет посылку.","source":"https://www.tiktok.com/search?q=huss%20valley%20delivery","status":"На проверку","types":["Trend-jack","AI animals","Story","Meme"],"recommendation":"Тестировать","id":"idea-28"},
{"notion":"https://app.notion.com/3adbd701fac981dc9dc364a039ae31fb","title":"Quiet on the Creek: кто первый нарушит тишину","date":"2026-07-30","session":"День","score":8.5,"speed":"Растёт","hook":"Все звери замерли и смотрят в камеру; зритель ждёт, кто первым сорвётся.","source":"https://www.tiktok.com/search?q=quiet%20on%20the%20creek%20trend","status":"На проверку","types":["Trend-jack","AI animals","Interactive","Meme"],"recommendation":"Тестировать","id":"idea-29"},
{"notion":"https://app.notion.com/3adbd701fac98101a84ae2c1a3c9547f","title":"Promiscuous Identity-Swap: четыре AI-зверя обмениваются лицами на каждом бите","date":"2026-07-30","session":"День","score":9.2,"speed":"Только появился","hook":"Каждый удар меняет лица, одежду и роли; зритель выбирает лучшую случайную комбинацию.","source":"https://www.tiktok.com/search?q=promiscuous%20identity%20swap%20trend","status":"На проверку","types":["Trend-jack","AI animals","Interactive","Meme"],"recommendation":"Стартовать первой","id":"idea-30"},
{"notion":"https://app.notion.com/3adbd701fac98186b2ce8e82ea4f80f8","title":"Foam Side-Eye Bounce: AI-капибара ловит взгляд и возвращается в танец","date":"2026-07-30","session":"День","score":9.0,"speed":"Растёт","hook":"Капибара танцует в пене, резко бросает side-eye в камеру и продолжает как ни в чём не бывало.","source":"https://www.tiktok.com/search?q=side%20eye%20bounce%20trend","status":"На проверку","types":["Trend-jack","AI animals","Meme"],"recommendation":"Сильный тест","id":"idea-31"},
{"notion":"https://app.notion.com/3adbd701fac981ff8eb166be6e39d508","title":"Bruno Zero Reaction: белый щенок не реагирует на конец света","date":"2026-07-30","session":"День","score":8.0,"speed":"Растёт","hook":"Вокруг рушится весь мир, а щенок спокойно продолжает смотреть в камеру.","source":"https://www.tiktok.com/search?q=zero%20reaction%20dog%20trend","status":"На проверку","types":["Trend-jack","AI animals","Meme","Story"],"recommendation":"Запасной формат","id":"idea-32"},
{"notion":"https://app.notion.com/3adbd701fac981cdb7bd301a013128c7","title":"IYO Tiny Tough Guy: хомяк угрожает соперникам в voice-chat","date":"2026-07-30","session":"День","score":8.5,"speed":"Растёт","hook":"Крошечный хомяк ведёт себя как самый опасный игрок сервера.","source":"https://www.tiktok.com/search?q=iyo%20tiny%20tough%20guy","status":"На проверку","types":["Trend-jack","AI animals","Meme"],"recommendation":"Тестировать","id":"idea-33"},
{"notion":"https://app.notion.com/3adbd701fac98160823d60f770371f15","title":"What Sound Does It Make?: звери озвучивают невозможную машину","date":"2026-07-30","session":"День","score":8.0,"speed":"Растёт","hook":"Зритель угадывает звук странного механизма до нелепого reveal.","source":"https://www.tiktok.com/search?q=what%20sound%20does%20it%20make%20trend","status":"На проверку","types":["Trend-jack","AI animals","Interactive","Meme"],"recommendation":"Запасной формат","id":"idea-34"},
{"notion":"https://app.notion.com/3adbd701fac9818187aa42df9d50c75e","title":"Saxophones Getting Louder: робот чинит провод — ломается вся реальность","date":"2026-07-30","session":"День","score":8.8,"speed":"Растёт","hook":"Каждый саксофон усиливает баг, пока город не превращается в глитч.","source":"https://www.tiktok.com/search?q=saxophones%20getting%20louder%20trend","status":"На проверку","types":["Trend-jack","Story","Meme","Satisfying"],"recommendation":"Сильный тест","id":"idea-35"},
{"notion":"https://app.notion.com/3adbd701fac9811d8706380483a8cecb","title":"Power Trading 2.0: звери торгуют суперспособностями","date":"2026-07-30","session":"День","score":8.6,"speed":"Растёт","hook":"Каждый обмен силы делает персонажей всё более нелепыми и опасными.","source":"https://www.tiktok.com/search?q=power%20trading%20trend","status":"На проверку","types":["Trend-jack","AI animals","Interactive","Story"],"recommendation":"Тестировать","id":"idea-36"},
{"notion":"https://app.notion.com/3adbd701fac981e8a1d5c5e2e45c9f87","title":"Kumar Method: капибара объявляет войну скучным экспертам","date":"2026-07-30","session":"Вечер","score":9.0,"speed":"Растёт","hook":"Капибара-гуру с серьёзным лицом выдаёт три абсурдно уверенных правила продуктивности.","source":"https://www.tiktok.com/search?q=kumar%20method%20trend","status":"На проверку","types":["Trend-jack","AI animals","Story","Meme"],"recommendation":"Сильный тест","id":"idea-37"},
{"notion":"https://app.notion.com/3adbd701fac981fba9a1ebd98af8ad8d","title":"100% Polyester Animal Edit: намеренно ужасный эдит капибары","date":"2026-07-30","session":"Вечер","score":8.5,"speed":"Растёт","hook":"Дешёвые переходы, плохой glow и слишком уверенная капибара превращают плохой монтаж в фишку.","source":"https://www.tiktok.com/search?q=100%20polyester%20edit%20trend","status":"На проверку","types":["Trend-jack","AI animals","Meme"],"recommendation":"Тестировать","id":"idea-38"},
{"notion":"https://app.notion.com/3adbd701fac9811e899791b581bd9340","title":"Petal-Web Hero: кот превращается в цветочно-паутинного героя","date":"2026-07-30","session":"Вечер","score":9.0,"speed":"Растёт","hook":"Белый кот касается лепестка и за три бита получает живую цветочную броню.","source":"https://www.tiktok.com/search?q=petal%20web%20hero%20trend","status":"На проверку","types":["Trend-jack","Story","Satisfying","Interactive"],"recommendation":"Сильный тест","id":"idea-39"},
{"notion":"https://app.notion.com/3adbd701fac981725b5a657fb55fb4cb","title":"Rush Hour Miscommunication: звери понимают просьбу наоборот","date":"2026-07-30","session":"Вечер","score":8.0,"speed":"Растёт","hook":"Обычная просьба запускает цепь всё более нелепых неправильных действий.","source":"https://www.tiktok.com/search?q=rush%20hour%20miscommunication%20trend","status":"На проверку","types":["Trend-jack","AI animals","Meme","Interactive"],"recommendation":"Запасной формат","id":"idea-40"},
{"notion":"https://app.notion.com/3adbd701fac981ad9824554846250906","title":"Netflix Documentary: кто украл последнее печенье?","date":"2026-07-31","session":"Утро","score":8.5,"speed":"Растёт","hook":"Сверхсерьёзный документальный тон расследует абсолютно ничтожное преступление.","source":"https://www.tiktok.com/search?q=netflix%20documentary%20parody%20trend","status":"На проверку","types":["Trend-jack","AI animals","Story","Meme"],"recommendation":"Тестировать","id":"idea-41"},
{"notion":"https://app.notion.com/3adbd701fac9818a9a0c8b28a65b35e","title":"Impossible Choice: Fantasy or Cyber City","date":"2026-07-31","session":"Утро","score":8.9,"speed":"Растёт","hook":"Один и тот же кадр одновременно раскрывается как сказочный и киберпанковый город; зритель выбирает сторону.","source":"https://www.tiktok.com/search?q=fantasy%20or%20cyber%20city%20choice","status":"На проверку","types":["Trend-jack","Interactive","Story"],"recommendation":"Сильный тест","id":"idea-42"},
{"notion":"https://app.notion.com/3adbd701fac9818a95a520eecbfcf208","title":"Bangladesh Grocery Store Chaos","date":"2026-07-31","session":"Утро","score":9.0,"speed":"Уже массовый","hook":"Крошечный магазин превращается в абсолютный хаос из людей, животных и летящих товаров.","source":"https://www.tiktok.com/search?q=bangladesh%20grocery%20store%20chaos","status":"На проверку","types":["Trend-jack","AI animals","Story","Meme"],"recommendation":"Сильный тест","id":"idea-43"},
{"notion":"https://app.notion.com/3adbd701fac981aba93e2114791a5fdc","title":"Question Swap: Password Cat Confession","date":"2026-07-31","session":"Утро","score":8.0,"speed":"Растёт","hook":"Кот случайно отвечает на вопрос, который ещё не был задан, и раскрывает пароль.","source":"https://www.tiktok.com/search?q=question%20swap%20trend","status":"На проверку","types":["Trend-jack","AI animals","Interactive","Meme"],"recommendation":"Запасной формат","id":"idea-44"},
{"notion":"https://app.notion.com/3adbd701fac981b3a49a7299ad65762f","title":"Worth the Money: Tiny Chef Big Reviews","date":"2026-07-31","session":"Утро","score":8.5,"speed":"Растёт","hook":"Крошечный шеф оценивает огромные блюда с чрезмерно серьёзным видом.","source":"https://www.tiktok.com/search?q=tiny%20chef%20big%20review","status":"На проверку","types":["Trend-jack","AI animals","Story","Meme"],"recommendation":"Тестировать","id":"idea-45"},
{"notion":"https://app.notion.com/3aebd701fac981118a8c3d929a12c95a","title":"Alien Package Unboxing: посылка, которую нельзя открывать","date":"2026-07-31","session":"День","score":8.5,"speed":"Растёт","hook":"Коробка с предупреждением сама раскрывается, а внутри живёт невозможная капсула.","source":"https://www.tiktok.com/search?q=alien%20package%20unboxing","status":"На проверку","types":["Trend-jack","Story","Interactive"],"recommendation":"Тестировать","id":"idea-46"},
{"notion":"https://app.notion.com/3aebd701fac9815b9b284c971c49a2fe","title":"Screens in Real Life: Computah перепрошивает улицу","date":"2026-07-31","session":"День","score":8.5,"speed":"Растёт","hook":"Умные очки показывают скрытые интерфейсы города и превращают автобус в звездолёт.","source":"https://www.tiktok.com/search?q=computah%20make%20x%20into%20y","status":"На проверку","types":["Trend-jack","Story","Meme"],"recommendation":"Тестировать","id":"idea-47"},
{"notion":"https://app.notion.com/3aebd701fac9818f9a511e0a72d88595","title":"Food ASMR Surgery: операция на десерте","date":"2026-07-31","session":"День","score":9.0,"speed":"Растёт","hook":"Желейный десерт становится пациентом: crack, peel, cut и светящаяся начинка.","source":"https://www.tiktok.com/search?q=food%20asmr%20surgery","status":"На проверку","types":["Trend-jack","Satisfying","Story"],"recommendation":"Сильный тест","id":"idea-48"},
{"notion":"https://app.notion.com/3aebd701fac981ccb6d74adfc37ac0f1","title":"NPC Energy Filter: фоновой персонаж становится главным","date":"2026-07-31","session":"День","score":8.5,"speed":"Растёт","hook":"Один шаг переключает героя из серого NPC-режима в cinematic main-character mode.","source":"https://www.tiktok.com/search?q=npc%20energy%20filter%20transformation","status":"На проверку","types":["Trend-jack","Interactive","Satisfying"],"recommendation":"Тестировать","id":"idea-49"},
{"notion":"https://app.notion.com/3aebd701fac981dbaf6953d9e88b375b","title":"SS26 Pet Runway: собаки в невозможных купальных костюмах","date":"2026-08-01","session":"Вечер","score":8.8,"speed":"Растёт","hook":"Псевдо-показ мод: собаки идут по улице в нелепых плавательных образах и кругах.","source":"https://www.tiktok.com/search?q=dog%20swimwear%20runway","status":"Новая","types":["Trend-jack","AI animals","Interactive"],"recommendation":"Сильный тест","id":"idea-50"},
{"notion":"https://app.notion.com/3aebd701fac9814b96be0c23a862e776","title":"Paparazzi Parade: флэш-вспышки меняют весь парад","date":"2026-08-01","session":"Вечер","score":9.1,"speed":"Растёт","hook":"Колонна проходит по городу, а каждая вспышка превращает костюмы, эпоху и персонажей.","source":"https://www.tiktok.com/search?q=paparazzi%20parade%20trend","status":"Новая","types":["Trend-jack","Story","Satisfying"],"recommendation":"Стартовать первой","id":"idea-51"},
{"notion":"https://app.notion.com/3aebd701fac981f5a21758e1044728ca","title":"Photo Booth Wrong Hero: занавес открывается — там совсем не тот","date":"2026-08-01","session":"Вечер","score":8.7,"speed":"Только появился","hook":"Милое трендовое начало заканчивается reveal потрёпанного сантехника в транспорте.","source":"https://www.tiktok.com/search?q=wrong%20hero%20reveal%20trend","status":"Новая","types":["Trend-jack","Meme","Story"],"recommendation":"Тестировать","id":"idea-52"},
{"notion":"https://app.notion.com/3aebd701fac981a59e38c10e74a0b982","title":"Not Very Nonchalant: фальшивый золотой фестиваль Нью-Йорка","date":"2026-08-01","session":"Вечер","score":8.7,"speed":"Растёт","hook":"Как будто настоящий городской ивент: золотая колонна идёт по Манхэттену под трендовый звук.","source":"https://www.tiktok.com/search?q=fake%20city%20festival%20parade","status":"Новая","types":["Trend-jack","Story","Interactive"],"recommendation":"Тестировать","id":"idea-53"},
{"notion":"https://app.notion.com/3b0bd701fac98115852bc2c7a32093fc","title":"Nervy Outfit Morph Relay","date":"2026-08-02","session":"Утро","score":9.1,"speed":"Растёт","hook":"Каждый bam меняет одежду и сам материал тела: ткань → стекло → дым → растения.","source":"https://www.tiktok.com/search?q=i%20just%20get%20so%20nervy%20outfit%20reveal","status":"Новая","types":["Trend-jack","Satisfying"],"recommendation":"Стартовать первой","id":"idea-54"},
{"notion":"https://app.notion.com/3b0bd701fac98167a6a8df84d4f18ecc","title":"How You Like Me Now — Dog Gym Boss","date":"2026-08-02","session":"Утро","score":8.7,"speed":"Растёт","hook":"Ленивый пёс превращается в exaggerated gym boss, но в финале выбирает лакомство.","source":"https://www.tiktok.com/search?q=how%20you%20like%20me%20now%20transformation","status":"Новая","types":["AI animals","Meme"],"recommendation":"Тестировать","id":"idea-55"},
{"notion":"https://app.notion.com/3b0bd701fac98111aeafd59ecd5acc03","title":"Big Boom Ant Takeover","date":"2026-08-02","session":"Утро","score":9.0,"speed":"Растёт","hook":"Одна крошка на ударе Big Boom раскрывается как муравьиный строительный мегаполис.","source":"https://www.tiktok.com/search?q=big%20boom%20in%20the%20room%20reveal","status":"Новая","types":["Trend-jack","AI animals","Story"],"recommendation":"Сильный тест","id":"idea-56"},
{"notion":"https://app.notion.com/3b0bd701fac981a799bedd3aa5729fd0","title":"Five-Color Memory Duel","date":"2026-08-02","session":"Утро","score":8.8,"speed":"Только появился","hook":"Игровой visual test: запомнить последовательность цветных всплесков до reveal.","source":"https://www.tiktok.com/search?q=color%20memory%20challenge%20effect","status":"Новая","types":["Interactive","Satisfying"],"recommendation":"Сильный тест","id":"idea-57"},
{"notion":"https://app.notion.com/3b0bd701fac9811d9c6aee69520909c3","title":"Invisible Skateboarder: одежда делает трюк без человека","date":"2026-08-02","session":"Вечер","score":8.5,"speed":"Только появился","hook":"Пустая одежда выполняет идеальный скейт-трюк; цветной след и loop провоцируют пересмотры.","source":"https://www.tiktok.com/search?q=boneless%20tiktok","status":"Новая","types":["Satisfying","Meme","Interactive"],"recommendation":"Тестировать","id":"idea-58"},
{"notion":"https://app.notion.com/3b0bd701fac9813b96cfed8b4e1af358","title":"Emotional Object Reactions: предметы слишком близко принимают слова","date":"2026-08-02","session":"Вечер","score":8.4,"speed":"Растёт","hook":"Обычный предмет слышит неприятную фразу, меняет лицо, цвет и материал, затем отвечает.","source":"https://www.tiktok.com/search?q=ai%20objects%20with%20feelings","status":"Новая","types":["Meme","Story","Interactive"],"recommendation":"Тестировать","id":"idea-59"},
{"notion":"https://app.notion.com/3b0bd701fac9815e9c2bc5eb99f4809f","title":"Celebrity Statue Prank: городская статуя внезапно оживает","date":"2026-08-02","session":"Вечер","score":8.6,"speed":"Растёт","hook":"Неподвижная статуя надувает жвачку, делает современный жест и меняет материал.","source":"https://www.tiktok.com/search?q=living%20statue%20prank","status":"Новая","types":["Trend-jack","Meme","Story"],"recommendation":"Тестировать","id":"idea-60"},
{"notion":"https://app.notion.com/3b0bd701fac981bc97d9e4c90ce777d8","title":"Breakfast Battle: тост против яйца под срочный аудиотренд","date":"2026-08-02","session":"Вечер","score":8.8,"speed":"Растёт","hook":"У тебя 30 минут спасти завтрак — кто победит? Два антропоморфных продукта дерутся строго по битам.","source":"https://www.tiktok.com/search?q=breakfast%20battle%20trend","status":"Новая","types":["Trend-jack","AI animals","Meme","Interactive"],"recommendation":"Сильный тест","id":"idea-61"}
];

const IMAGE_FILES = ["41-magic_paws_in_a_neon_bath.png","00-three-kittens-3-colors-original.png","18-неоновая_доска_идей_четыре_водных_чуда.png","42-color_squad_splash_party.png","08-four_panel_liquid_trend_board.png","47-white_chef_cat_from_bland_to_brilliant.png","24-swirling_sink_of_endless_colors.png","08-four_panel_liquid_trend_board.png","02-four_vibrant_tiktok_trend_ideas.png","44-water_magic_trend_idea_board.png","45-three_kittens_three_colorful_splashes.png","43-four_part_vibrant_tiktok_experiment_collage.png","28-four_trendy_short_video_concepts.png","12-four_panel_tiktok_trend_board.png","31-sassy_neon_bubble_bath_cat.png","17-four_panel_viral_trend_dashboard.png","21-four_panel_tiktok_trend_thumbnail_grid.png","21-four_panel_tiktok_trend_thumbnail_grid.png","21-four_panel_tiktok_trend_thumbnail_grid.png","16-muted_mop_to_neon_groove.png","32-absurd_creature_parade.png","15-fourpanel_trend_ideas_collage.png","29-puppy_and_plumber_on_transit.png","37-you_need_to_create_a_succinct_title_for_the_image.png","14-you_choose_neon_vote_show.png","38-compressed_raccoon_wizard_vortex.png","04-tiktok_meme_trend_dashboard.png","13-trend_collage_bears_corn_otters_plushies.png","09-meme_trend_collage_four_quirky_scenes.png","46-neon_identity_swap_party.png","19-neon_capybara_foam_party.png","29-puppy_and_plumber_on_transit.png","13-trend_collage_bears_corn_otters_plushies.png","23-four_viral_tiktok_idea_panels.png","34-насыщенный_гид_трендов_кот_порталы_иллюзии_и_тр.png","36-viral_trend_moodboard_four_ai_powered_ideas.png","20-four_panel_trend_roundup_collage.png","20-four_panel_trend_roundup_collage.png","06-floral_web_guardian_cats.png","30-crowded_commute_misstep.png","05-viral_meme_trend_collage_chill_chaos_and_japan.png","11-four_part_neon_trend_collage.png","03-absurd_animals_in_times_square.png","10-russian_trend_pitch_board.png","11-four_part_neon_trend_collage.png","40-four_panel_tiktok_idea_board.png","27-четыре_идеи_для_tiktok_трендов.png","26-four_viral_tiktok_concepts.png","51-a_split_juxtaposed_cinematic_scene_inside_a_city_b_4_batch_4.png","33-dog_swimwear_parade_spectacular.png","48-a_lively_street_parade_scene_in_warm_golden_light_3_batch_3.png","22-bus_ride_with_a_handyman.png","07-paris_parade_drummers_by_the_arc_de_triomphe.png","39-four_viral_tiktok_ideas_collage.png","49-a_vibrant_high_detail_whimsical_street_scene_in_2_batch_2.png","04-tiktok_meme_trend_dashboard.png","01-golden_parade_through_downtown.png","50-a_vibrant_high_detail_colorful_street_parade_sce_1_batch_1.png","51-a_split_juxtaposed_cinematic_scene_inside_a_city_b_4_batch_4.png","35-parade_of_fruit_and_fantasy_creatures.png","25-parade_of_playful_bread_pets.png"];

async function download(id) {
  const urls = [
    `https://drive.usercontent.google.com/download?id=${id}&export=download&confirm=t`,
    `https://drive.google.com/uc?export=download&id=${id}&confirm=t`,
  ];
  let last;
  for (const url of urls) {
    try {
      const r = await fetch(url, { redirect: "follow" });
      if (!r.ok) throw new Error(`${r.status} ${r.statusText}`);
      const buf = new Uint8Array(await r.arrayBuffer());
      if (buf.length < 1000000) throw new Error(`download suspiciously small: ${buf.length}`);
      return buf;
    } catch (e) { last = e; }
  }
  throw last;
}

await rm("dist", { recursive: true, force: true });
await mkdir("dist/assets", { recursive: true });
for (const [id, name] of PARTS) {
  console.log("Downloading", name);
  const zip = await download(id);
  const files = unzipSync(zip);
  for (const [fileName, bytes] of Object.entries(files)) {
    if (fileName.endsWith("/")) continue;
    const dest = path.join("dist", fileName);
    await mkdir(path.dirname(dest), { recursive: true });
    await writeFile(dest, bytes);
  }
}

const payload = IDEAS.map((idea, i) => ({ ...idea, image: `assets/${IMAGE_FILES[i]}` }));
await writeFile("dist/ideas.json", JSON.stringify(payload, null, 2), "utf8");

const html = String.raw`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Water/Colors — Visual Review</title><style>
:root{--bg:#0a0d14;--line:#2a3344;--text:#f5f7fb;--muted:#a5afbf;--accent:#55d8ff;--pink:#ff5ca8;font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text)}a{color:var(--accent)}.wrap{width:min(1800px,calc(100% - 36px));margin:auto}header{padding:42px 0 22px}h1{font-size:clamp(2.2rem,5vw,4.8rem);line-height:1;margin:.2em 0}.sub{color:var(--muted);max-width:900px;line-height:1.5}.tools{position:sticky;top:0;z-index:9;background:#0a0d14ee;backdrop-filter:blur(15px);border-block:1px solid var(--line);padding:12px 0}.toolrow{display:grid;grid-template-columns:1fr 220px 220px;gap:10px}input,select,button{font:inherit;color:var(--text);background:#111827;border:1px solid var(--line);border-radius:10px;padding:11px}.list{padding:28px 0 80px}.row{display:grid;grid-template-columns:minmax(260px,38%) 1fr;gap:28px;border-bottom:1px solid var(--line);padding:28px 0}.img{width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:16px;border:1px solid var(--line);cursor:zoom-in}.meta{display:flex;gap:7px;flex-wrap:wrap}.pill{font-size:.75rem;color:#cbd4e3;border:1px solid var(--line);padding:5px 8px;border-radius:999px}h2{font-size:clamp(1.35rem,2.2vw,2.2rem);margin:12px 0}.hook{font-size:1.05rem;line-height:1.6;color:#e0e5ed}.rating{margin-top:16px;padding:14px;border:1px solid var(--line);border-radius:12px}.rating strong{display:block;margin-bottom:8px}.nums{display:grid;grid-template-columns:repeat(10,1fr);gap:6px}.rate{padding:9px 2px}.rate.on{background:linear-gradient(135deg,var(--pink),#7458ff);border-color:transparent}.links{display:flex;gap:14px;flex-wrap:wrap;margin-top:14px}.modal{display:none;position:fixed;inset:0;z-index:20;background:#000e;align-items:center;justify-content:center;padding:20px}.modal.open{display:flex}.modal img{max-width:96vw;max-height:92vh;object-fit:contain}@media(max-width:850px){.toolrow{grid-template-columns:1fr}.row{grid-template-columns:1fr}}
</style></head><body><header><div class="wrap"><b style="color:var(--accent)">WATER / COLORS · ORIGINAL CHAT ARCHIVE</b><h1>Все идеи и исходные картинки</h1><p class="sub">61 идея в хронологическом порядке. Все 52 сохранившиеся ImageGen-картинки из чата используются хотя бы один раз. Оценки сохраняются в браузере.</p></div></header><div class="tools"><div class="wrap toolrow"><input id="q" placeholder="Поиск по идеям…"><select id="sort"><option value="old">С начала чата</option><option value="new">Сначала новые</option><option value="score">По вирусности</option><option value="mine">По моей оценке</option></select><select id="filter"><option value="all">Все идеи</option><option value="fav">Мои 8–10</option><option value="rated">Оценённые</option></select></div></div><main class="wrap"><section class="list" id="list"></section></main><div class="modal" id="modal"><img id="big" alt=""></div><script>
const K='wc-original-ratings-v1';let R=JSON.parse(localStorage.getItem(K)||'{}');let DATA=[];const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function render(){let q=$('#q').value.toLowerCase(),sort=$('#sort').value,f=$('#filter').value;let a=DATA.filter(x=>{let r=R[x.id]||0,t=(x.title+' '+x.hook+' '+x.types.join(' ')).toLowerCase();return(!q||t.includes(q))&&(f==='all'||f==='fav'&&r>=8||f==='rated'&&r)});a.sort((x,y)=>sort==='new'?y.date.localeCompare(x.date):sort==='score'?y.score-x.score:sort==='mine'?(R[y.id]||0)-(R[x.id]||0):x.date.localeCompare(y.date));$('#list').innerHTML=a.map((x,i)=>{let r=R[x.id]||0;return `<article class="row"><img class="img" loading="lazy" src="${x.image}" data-src="${x.image}" alt="${esc(x.title)}"><div><div class="meta"><span class="pill">${x.date}</span><span class="pill">${esc(x.session)}</span><span class="pill">${esc(x.speed)}</span><span class="pill">ChatGPT ${x.score.toFixed(1)}/10</span>${x.types.map(t=>`<span class="pill">${esc(t)}</span>`).join('')}</div><h2>${i+1}. ${esc(x.title)}</h2><p class="hook">${esc(x.hook)}</p><div class="rating"><strong>Оценка Димы: ${r||'—'} / 10</strong><div class="nums">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<button class="rate ${r===n?'on':''}" data-id="${x.id}" data-n="${n}">${n}</button>`).join('')}</div></div><div class="links"><a target="_blank" rel="noopener" href="${x.source}">Источник / тренд ↗</a><a target="_blank" rel="noopener" href="${x.notion}">Запись Notion ↗</a><a target="_blank" rel="noopener" href="${x.image}">Оригинал ↗</a></div></div></article>`}).join('');document.querySelectorAll('.rate').forEach(b=>b.onclick=()=>{let id=b.dataset.id,n=+b.dataset.n;R[id]=R[id]===n?0:n;if(!R[id])delete R[id];localStorage.setItem(K,JSON.stringify(R));render()});document.querySelectorAll('.img').forEach(im=>im.onclick=()=>{$('#big').src=im.dataset.src;$('#modal').classList.add('open')})}
fetch('ideas.json').then(r=>r.json()).then(d=>{DATA=d;render()});['q','sort','filter'].forEach(id=>$('#'+id).addEventListener(id==='q'?'input':'change',render));$('#modal').onclick=()=>$('#modal').classList.remove('open');
</script></body></html>`;
await writeFile("dist/index.html", html, "utf8");
console.log(`Built ${payload.length} ideas and ${new Set(IMAGE_FILES).size} original images`);
